Repository onivim/oni2, pull requests merged in 2021-06, with the labels that each got.

#3661 feat(search): add include/exclude file boxes
  CHANGES_CURRENT.md
  src/Core/Ripgrep.re
  src/Core/Ripgrep.rei
  src/Feature/Search/Feature_Search.re
  src/Service/Ripgrep/Service_Ripgrep.re
  src/Service/Ripgrep/Service_Ripgrep.rei
Labels: N-screenshot

#3607 fix(font/#3605): Fix crash when specifying empty guifont
  CHANGES_CURRENT.md
  src/Core/Utility/StringEx.re
  src/Core/VimSetting.re
  src/Feature/Editor/EditorConfiguration.re
  src/Service/Font/Service_Font.re
  src/Store/VimStoreConnector.re
Labels: A-font

#3668 fix(ux/#3569) close menu if it's already open
  CHANGES_CURRENT.md
  src/Feature/MenuBar/Feature_MenuBar.re
Labels: B-license-key

#3695 fix(extensions/#3335): Fix add to user dictionary command
  CHANGES_CURRENT.md
  src/Feature/Exthost/Feature_Exthost.re
Labels: N-screenshot
